apiVersion: v1
kind: Secret
metadata:
  name: postgres-backup-credentials
  labels:
    app: backup-cronjob
type: Opaque
stringData:
  # Credentials pour les bases PostgreSQL
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  # Services des bases de données
  DB_FR_HOST: "db-fr-service"
  DB_FR_PORT: "5432"
  DB_FR_NAME: "health_data_fr"
  DB_US_HOST: "db-us-service"
  DB_US_PORT: "5432"
  DB_US_NAME: "health_data_us"
  DB_CH_HOST: "db-ch-service"
  DB_CH_PORT: "5432"
  DB_CH_NAME: "health_data_ch"
