FROM postgres:latest

# Copier uniquement le schema US
COPY init_us/schema_us.sql /docker-entrypoint-initdb.d/01-schema.sql

# Donner les bonnes permissions
RUN chmod +x /docker-entrypoint-initdb.d/*.sql

EXPOSE 5432

EXPOSE 5432
