FROM postgres:latest

# Copier uniquement le dump US
COPY init_us/dumpus.sql /docker-entrypoint-initdb.d/01-dumpus.sql

# Donner les bonnes permissions
RUN chmod +x /docker-entrypoint-initdb.d/*.sql

EXPOSE 5432
