FROM postgres:latest

# Copier uniquement le dump FR
COPY initdb/dump.sql /docker-entrypoint-initdb.d/01-dump.sql

# Donner les bonnes permissions
RUN chmod +x /docker-entrypoint-initdb.d/*.sql

EXPOSE 5432
