events {}

http {
    server {
        listen 80;

        location /api/fr/ {
            rewrite ^/api/fr/(.*)$ /$1 break;
            proxy_pass http://backend-fr-service:8084/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /api/us/ {
            rewrite ^/api/us/(.*)$ /$1 break;
            proxy_pass http://backend-us-service:8084/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /api/ch/fr/ {
            rewrite ^/api/ch/fr/(.*)$ /$1 break;
            proxy_pass http://backend-ch-fr-service:8084/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /api/ch/en/ {
            rewrite ^/api/ch/en/(.*)$ /$1 break;
            proxy_pass http://backend-ch-en-service:8084/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /api/ch/de/ {
            rewrite ^/api/ch/de/(.*)$ /$1 break;
            proxy_pass http://backend-ch-de-service:8084/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /api/ch/it/ {
            rewrite ^/api/ch/it/(.*)$ /$1 break;
            proxy_pass http://backend-ch-it-service:8084/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            proxy_pass http://frontend-service:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}