apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-fr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-fr
  template:
    metadata:
      labels:
        app: backend-fr
    spec:
      containers:
        - name: backend-fr
          image: my_backend_image:latest
          imagePullPolicy: Never #cette ligne empêche Kind de télécharger l'image depuis internet, il prends uniquement la locale
          ports:
            - containerPort: 8084
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "admin"
            - name: POSTGRES_HOST
              value: "db-fr"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "bdd_mspr"
            - name: USER_COUNTRY
              value: "FR"
            - name: LANG
              value: "fr"