apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-us
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-us
  template:
    metadata:
      labels:
        app: db-us
    spec:
      containers:
        - name: db-us
          image: mspr-postgres-us:latest
          imagePullPolicy: IfNotPresent #cette ligne empêche Kind de télécharger l'image depuis internet, il prends uniquement la locale
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_HOST
              value: db-us
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "admin"
            - name: POSTGRES_DB
              value: "bdd_us"